version: "1"
services:
    webserver:
        build: docker/php
        ports:
            - "0.0.0.0:${APP_PORT}:80"
            - "0.0.0.0:${APP_PORT_SSL}:443"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - ./docker/ssl:/etc/ssl/docker
        command: sh -c "./build.sh && apachectl -D FOREGROUND"
        restart: always
        depends_on:
            mysql:
                condition: service_started
            redis:
                condition: service_started
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "0.0.0.0:${DB_EXPOSE_PORT}:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./mysql/lib:/var/lib/mysql
            - ./mysql/conf:/etc/mysql/conf.d
        restart: always
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: always
